#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_w

# EKF2: Vision position and heading
param set-default EKF2_AID_MASK 24 # 24 = 000011000 = Vision position fusion + Vision yaw fusion
#param set-default EKF2_AID_MASK 280 #  280 = 100011000 = Vision position fusion + Vision yaw fusion + Vision velocity fusion
param set-default EKF2_HGT_MODE 3   #3   # Vision
param set-default COM_OBS_AVOID 1

#param set-default EKF2_ASP_DELAY 250
param set-default EKF2_EV_DELAY 150
param set-default EKF2_EV_POS_X 0.0
param set-default EKF2_EV_POS_Y 0.0
param set-default EKF2_EV_POS_Z 0.0

param set-default MPC_XY_VEL_MAX 1.0
param set-default MPC_Z_VEL_ALL 1.0
